### ISSUE TITLE
Add toggle buttom for features

### ISSUE THREAD

**Issue by YaQia** [amarullz/windowgestures#1]
By searching through which plugin could handle gesture supports in Gnome 45, I found this one. I love your great work. However there are several features not very useful for me. I need a way to toggle features like:
1. reverse `move window to left/right workspaces`.
2. disable `snap window to left/right`
3. disable `resize window`

Well, another small thing: In my computer, moving a window and moving the cursor is not consistent. (My resolution scaling is 200%.)

**Comment by amarullz** [comment]
Yes, I will add more config. Enable/disable function seems nice.

**Comment by YaQia** [comment]
> For moving, maybe you can try to change acceleration config.
I might made you misunderstood. Here is the problem of moving a window:

[录屏 2023-10-10 21-28-46.webm](https://github.com/amarullz/windowgestures/assets/61108050/1a57d096-f5df-42fe-a74c-004bab20ceff)
As the video shows, pointer/cursor is not moving with the window.

And I have tested that the move in 100% resolution scaling is okay for me.

**Comment by amarullz** [comment]
Ah I see. will try in scaling display.

I need to know where to get the scaling setting value.

**Comment by amarullz** [comment]
![Screenshot from 2023-10-10 21-54-57](https://github.com/amarullz/windowgestures/assets/1386831/18e8c191-363d-4f46-9f56-9340ed3370b8)
On progress

**Comment by amarullz** [comment]
Can you test this pre-release?
https://github.com/amarullz/windowgestures/releases/tag/2.1-pre1

**Comment by YaQia** [comment]
Wow, how fast you are! I have tested those toggle buttons, these are exactly what I need!

The snapping window function is awesome, love it!

**Comment by amarullz** [comment]
Can I close it?

**Comment by YaQia** [comment]
Well, #2 is still pending, I think we can probably wait for that one to be finished.

**Comment by amarullz** [comment]
About cursor pointer, I cannot reproduce the problem when I scaling the display.
But It will not hapenning if you `Use Active Window` anyway.

**Comment by YaQia** [comment]
> Can I close it?
Maybe reopen #2 is more appropriate? I will reopen it later.

**Comment by YaQia** [comment]
> About cursor pointer, I cannot reproduce the problem when I scaling the display. But It will not hapenning if you `Use Active Window` anyway.

Yeah, I can hold Super to do that too. I noticed that bug but the feature is not that useful for me. After all, thank you for your coding!
