### ISSUE TITLE
gestures should be ignored in overview and show applications

### ISSUE THREAD

**Issue by YaQia** [amarullz/windowgestures#10]
As the title says, it is not appropriate to use gestures in `overview` and `show applications`.

**Comment by amarullz** [comment]
Yes, will fix it. But I need to find a way to know if it in overview state.

**Comment by amarullz** [comment]
It also related with #11 - About list of state that gesture should be ignored

**Comment by amarullz** [comment]
Fixed by this commit: https://github.com/amarullz/windowgestures/commit/e0a6e792bd52cd081189629435b44347af338473

**Comment by amarullz** [comment]
Update can be tested at 3-beta1
https://github.com/amarullz/windowgestures/releases/tag/3.0-beta1

**Comment by YaQia** [comment]
I guess this issue is fixed. I will close it.
