### ISSUE TITLE
Gesture on desktop cause issues

### ISSUE THREAD

**Issue by sidevesh** [amarullz/windowgestures#11]
[Screencast from 2023-10-11 15-01-35.webm](https://github.com/amarullz/windowgestures/assets/17254413/89b6f50f-bf1b-4c56-9295-1b69716be9a4)
I am using DING extension for desktop icons in case that may be relevant.

**Comment by amarullz** [comment]
I suspect you use dash to dock right?
Try not hover the pointer above the dock. See if it still doing it. If it not, I know the solution but need to try dash to dock (I don't use it)

**Comment by sidevesh** [comment]
If the pointer is on the dock then the issue does not happen, it only happens if pointer is not on the dock and on the desktop.

**Comment by amarullz** [comment]
Hmm, I install dash to dock & don't have that problem. Do you have other extension that have to do with desktop. It's like a desktop is some kind of window.

**Comment by amarullz** [comment]
ok will try it

**Comment by amarullz** [comment]
Ah.. I see 😝 .. Ubuntu has it, and I disabled it,...

**Comment by amarullz** [comment]
Fixed in last commit https://github.com/amarullz/windowgestures/commit/234591cebbf330d55286549df1d60ae2a398d452

Try this version:
[windowgestures@extension.amarullz.com.zip](https://github.com/amarullz/windowgestures/files/12868747/windowgestures%40extension.amarullz.com.zip)

**Comment by sidevesh** [comment]
That version did not work, fails to load: `GLib.FileError: Failed to open file “/home/sidevesh/.local/share/gnome-shell/extensions/windowgestures@extension.amarullz.com/schemas/gschemas.compiled”: open() failed: No such file or directory`

**Comment by amarullz** [comment]
How did you install it? just replace existing?

**Comment by sidevesh** [comment]
that fixed the install and I can confirm that the issue does not happen anymore.
