### ISSUE TITLE
X11 support?

### ISSUE THREAD

**Issue by andrewaclear** [amarullz/windowgestures#12]
Does this extension work on Xorg?

**Comment by amarullz** [comment]
About this issue: https://github.com/amarullz/windowgestures/issues/3#issuecomment-1755744618

**Comment by andrewaclear** [comment]
I see thanks. Darn it's just too bad cause I have to use X11 for my NVIDIA driver and used those gestures before all the time. I wonder what kind of change GNOME did to lose support for this?
