### ISSUE TITLE
Opening app drawer with 3-finger gesture isn't 1 to 1

### ISSUE THREAD

**Issue by tolis626** [amarullz/windowgestures#14]
Hi. First off, thank you for your work on improving Gnome's honestly lackluster gestures and making them amazing. Now, like many others, I was using the Gesture Improvements extension and am trying to move to this one for Gnome 45. Right out of the box I appreciate the added functionality of your extension, but there's a couple of pain points for me, which I think would be rather easy to solve on your end. First one is, when I set the 3-finger swipe down gesture to open Gnome's app drawer, the gesture doesn't correspond to a 1-to-1 action on the screen like all other gestures, but rather I have to complete the gesture and then I'm in the app drawer with no animation, which is jarring. Adding to that, there is no option for a cyclic overview navigation, so let's say I'm in the app drawer, swiping up with 3 fingers does nothing, I have to swipe down twice to go back to the main screen, whereas with GE's cyclic function I could just swipe up once and voila. These are pretty small, nitpicky things, but they are missing and I wanted to report on them so that your already excellent work becomes even better.

Again, thanks a lot!

**Comment by amarullz** [comment]
yea I know it, in last commit I try to implement it but still not smooth. Because I still want to make swipe down to customizable, in gesture Improvements swipe down is fixed for app drawer. +note it just a month old extension & still growing.

**Comment by tolis626** [comment]
Of course I undestand why things are the way they are. Don't take this as ungrateful pressure, this is not that. I am currently using WG and it's amazing. Honestly, the potential to be better than the already amazing GE is there, so I just wanted to provide feedback to make it even better. If there is a way to have a continuous, smooth cyclic animation when it's not expected to do other stuff within the same gesture pattern, that would be amazing. If not, I can live with that. 

Cheers!

**Comment by amarullz** [comment]
I mean I will implement it, but with cleaner and less event hook as possible, and still finding a better way for it.

I always prevent it from messing around with the original gnome gesture. Still learning more how the shell works.

If you try it from first version you don't even have any customizable 😅

**Comment by tolis626** [comment]
Nah man, screw Gnome's gestures, go nuts, hahahaha. 😄 

Sweet, looking forward to seeing what you'll come up with! Thanks for all the hard work man, really appreciate it! :)
