### ISSUE TITLE
Add "move window" option

### ISSUE THREAD

**Issue by amivaleo** [amarullz/windowgestures#16]
Hi!

Some time ago I used to use touchegg on X11 which allows to move windows by dragging them with 3 or 4 fingers.

I really miss that feature and I believe it could be much appreciated.

Can you please consider adding that feature to your extension, please?

**Comment by amarullz** [comment]
It's already implemented with 4 finger swipe down or on last commit you can move it with touch hold four fingers then move

**Comment by amivaleo** [comment]
> It's already implemented with 4 finger swipe down or on last commit you can move it with touch hold four fingers then move

That's good! I'll wait for it to land in EGO. Thanks :)
