### ISSUE TITLE
Maximizing gesture should be applied for current active window rather than the window under the pointer

### ISSUE THREAD

**Issue by YaQia** [amarullz/windowgestures#2]
I think this might be another feature, so I opened another issue.

As the title says, most gestures should not rely on the cursor/pointer position. Under pointer gestures seem to be suitable for touchscreen rather.

**Comment by amarullz** [comment]
Nice idea. But it should be configurable.
will try implementing it

**Comment by amarullz** [comment]
merge with issue #1

**Comment by YaQia** [comment]
I missed the toggle button for active window. Sorry for that. But I think disabling cursor moving when moving the window is a good choice.  So I am pleased with the current implementation.
