### ISSUE TITLE
Window become invisible after closing it by gesture (four finger down -> up)

### ISSUE THREAD

**Issue by Nikitf777** [amarullz/windowgestures#28]
When an application, for expample, has unsaved changes, it will ask you about saving your work instead of instant closure. And if such application is closed by gesture, it will become invisible.

[Screencast from 2024-04-15 17-18-11.webm](https://github.com/amarullz/windowgestures/assets/127026067/c3f406e7-d8bd-4cbc-997e-c3b7739479a9)

**Comment by amarullz** [comment]
fixed at ver 7
