### ISSUE TITLE
Window snapping not working

### ISSUE THREAD

**Issue by retroflexivity** [amarullz/windowgestures#35]
Snapping windows with gestures isn't working — neither when swiping up then to side nor when moving the window. Maximizing by the same means work properly. 

https://github.com/amarullz/windowgestures/assets/49839603/052de537-e169-4e16-be1e-a2f88c5e64b0

Gnome 46, but it persisted on 45 as well

**Comment by thyttan** [comment]
Hi! Did you perhaps change the keyboard shortcut, either through Gnome settings or elsewhere? That would stop the corresponding gestures working.

**Comment by retroflexivity** [comment]
Wow, that's an old one. Yes, I probably did. I'm not using Gnome anymore though...
