### ISSUE TITLE
Gnome 47?

### ISSUE THREAD

**Issue by pnguyen72** [amarullz/windowgestures#42]
As far as I can tell, everything works if you just add "47" to the metadata.

**Comment by manab-debnath** [comment]
Just head over to "~/.local/share/gnome-shell/extensions/windowgestures@extension.amarullz.com/metadata.json" here and add "47" to "shell-version" then restart your computer and you good to go.

**Comment by mario-tux** [comment]
I applied the trick days ago. It is a reminder for the author to make its extension available on the central repository for all the users.

Thanks anyway.

**Comment by pnguyen72** [comment]
@manab-debnath It's not good to go. The issue is this extension is not on EGO, many people wouldn't know it exists. I open the issue to ask the author to update the metadata so that the extension will be more widely available.

**Comment by amarullz** [comment]
updated
