### ISSUE TITLE
Add a setting to disable fullscreen window manipulation

### ISSUE THREAD

**Issue by sidevesh** [amarullz/windowgestures#5]
Allow to disable the behavior of making the window fullscreen when its already maximized

**Comment by amarullz** [comment]
![Screenshot from 2023-10-11 17-33-52](https://github.com/amarullz/windowgestures/assets/1386831/ee6d844d-429c-46c3-820c-07b8a40c240b)

Config has been added into latest commit https://github.com/amarullz/windowgestures/commit/d8b37b7f7ccc5a087d2b35fea277d015e9805f76

**Comment by sidevesh** [comment]
thanks! Closing this.
