### ISSUE TITLE
Show desktop gesture should animate all windows out of the view

### ISSUE THREAD

**Issue by sidevesh** [amarullz/windowgestures#7]
This is similar to how Mac OS show desktop gesture and gnome-gesture-improvements implements this.

**Comment by amarullz** [comment]
I still learn how to do it, and this is exactly what I want to do if I have a "clean" & right way to do it. I don't want to include any unnecessary dependency.

Not just for show desktop. Also switch window workspace animations, minimize animation, etc. All interpolation should be match with Gesture state.

**Comment by sidevesh** [comment]
That sounds great! you have already implemented a ton here and I would not have been able to upgrade to Gnome 45 without this extension, thanks a lot!

**Comment by amarullz** [comment]
[Screencast from 2023-10-12 09-28-17.webm](https://github.com/amarullz/windowgestures/assets/1386831/b1f03d31-2223-4867-b166-873d9cfadf94)

Implementing adaptive indicator. minimize, close, show desktop

**Comment by amarullz** [comment]
Don't close yet. I have a better implementation :)

**Comment by amarullz** [comment]
New Transition Implementation. 🤩🤩

[Screencast from 2023-10-12 11-17-18.webm](https://github.com/amarullz/windowgestures/assets/1386831/453de74f-20d5-4b7b-bc42-4477156209f7)

**Comment by amarullz** [comment]
Update can be test at 3-beta1
https://github.com/amarullz/windowgestures/releases/tag/3.0-beta1
