### ISSUE TITLE
Back Forward navigation or other actions (global or per-app) using three finger hold and swipe left / right gesture

### ISSUE THREAD

**Issue by sidevesh** [amarullz/windowgestures#9]
Adding only to track things that gnome-gesture-improvements had implemented,
honestly don't see this personally as too important since most GTK4 apps already have overscroll navigation and chromium also supports this on Wayland if enabled using launch flags.

**Comment by amarullz** [comment]
What actuality Back Forward navigation is?

**Comment by sidevesh** [comment]
[Screencast from 2023-10-11 14-15-16.webm](https://github.com/amarullz/windowgestures/assets/17254413/3bb8d278-d8fd-4dc6-b17c-a3bce327da14)
This is what that looks like, this is built into chromium on wayland but  gnome-gesture-improvements allowed to do this on every app with 3 finger hold and swipe left / right, and it also allowed for setting the action to do on that gesture per app,
so for example in the Photo Viewer you can swipe between photos left and right using the gesture.
It also added teh arrow animation that you see in the video to every winfow when using that gesture.

**Comment by amarullz** [comment]
It's just back/forward hardware button (for action) right? but with interface arrow. But I still don't know how to implementing that back arrow indicator.

**Comment by sidevesh** [comment]
Yes, correct, it just triggers the back forward key events

**Comment by amarullz** [comment]
Can you give me video that works in another apps, like a photos.

**Comment by sidevesh** [comment]
I can't since upgrading to Gnome 45 gnome-gesture-improvements just does not work,
the way it worked in gnome-gesture-improvements is that you can specify what the back and forward gestures did per app by setting a keyboard shortcut,
so I think for the Photos app it was set to left and right arrow.

**Comment by sidevesh** [comment]
no, so the video I sent is chromium's built in overscroll navigation indicator, not related to gnome or the extension at all,
gnome-gesture-improvements just mimicked chromium's back and forward indicator animation for its own hold 3 finger and swipe gesture,
and that mimicked arrow indicator was visible in all apps, when using gnome-gesture-improvements's gesture,
let me know if that did not make sense.

**Comment by amarullz** [comment]
Maybe the chromium one is also `mimicked arrow` 🫣

**Comment by amarullz** [comment]
Yes, it was mimicked arrow: https://github.com/harshadgavali/gnome-gesture-improvements/blob/main/extension/src/animations/arrow.ts

**Comment by amarullz** [comment]
Can you test this update?

[windowgestures@extension.amarullz.com.zip](https://github.com/amarullz/windowgestures/files/12883988/windowgestures%40extension.amarullz.com.zip)

**Comment by sidevesh** [comment]
https://github.com/amarullz/windowgestures/assets/17254413/e405fe9e-c6c7-4c46-8bb0-55b8af362a5a

It conflicts with pinch to zoom I guess, sometimes it works, sometimes it does not,
in this video back gesture isn't working but forward is,
when I had tried earlier, back was working but forward wasn't and back left a faint back arrow even after gesture ended.

Also this should not be configurable to pinch at all since its a very back UX, and conflicts with expectation of pinch is for zoom and does not feel natural at all.
